### ISSUE TITLE
Crash on Gummiship

### ISSUE THREAD

**Issue by Nona9614** [Zurphing/DoublePlus#2]
After installing either via the old way (KHPCPatchManager) or the new way (OpenKH) will crash in the following steps:

1. Complete the first time Hollow Bastion
2. Enter any of the gummi ship routes
3. Start the gummiship mission

After this the animation of ship departure, the game will crash.

If helps, I tried either with a native blueprint and a custom ship.

**Comment by Zurphing** [comment]
Not a Double Plus related crash. Currently, OpenKH's Panacea, which is what is used to dynamically load mods using OpenKH's Mod Manager will crash in trying to load Gummi Ship missions. Either install the GummiSkip lua script, or remove the DBGHelp.dll file from your games installation folder in order to fix the issue.
Closing.

**Comment by cannon9009** [comment]
> Currently, OpenKH's Panacea, which is what is used to dynamically load mods using OpenKH's Mod Manager will crash in trying to load Gummi Ship missions.

Has this issue been fixed in newer OpenKH versions? It's been half a year, so I was just wondering.
